### PR TITLE
Add ULL and CCR terms and links

### PR DESCRIPTION
**Pull request by tijmenbaarda**
Add information to Excel file.

### CODE REVIEW

**Comment by ar-jan** [comment]
Huh, all the CCR urls 404.

Maybe the terms should be standardized for case (all lower?) and use of spaces (wit space?)? (e.g. `prepositional Complement`, `OrdinalNumeral`).

Nit: ull term `positive` without corresponding URL (remove I guess).

**Review by ar-jan — COMMENTED** [review]
Huh, all the CCR urls 404.

Maybe the terms should be standardized for case (all lower?) and use of spaces (with space?)? (e.g. `prepositional Complement`, `OrdinalNumeral`).

Nit: ull term `positive` without corresponding URL (remove I guess).

**Comment by tijmenbaarda** [comment]
Hmm, strange that the URIs don't work. They are still referred to:
https://vocabularies.clarin.eu/clavas/ccr/en/page/?uri=http%3A%2F%2Fhdl.handle.net%2F11459%2FCCR_C-1232_2b532c10-f973-e6aa-bba5-2e752fcec1d2
It seems that the URIs are correct but that there is a problem with the Clarin pages.

**Comment by tijmenbaarda** [comment]
The terms should be standardized indeed, either to what is in `skos:notation` (camelcase) or `skos:prefLabel` (with spaces). Since we already include the URIs, I would suggest we go for the skos:prefLabel here.

**Comment by ar-jan** [comment]
> I would suggest we go for the skos:prefLabel here.

Sounds good

**Comment by tijmenbaarda** [comment]
Apparently `skos:prefLabel` has been applied consistently, but the labels are not consistent. So we don't make any further changes here.

**Pull request merged**
